//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokémon
    {
        public string pName { get; set; }
        public string nickname { get; set; }
        public int pLevel { get; set; }
        public int pId { get; set; }
        public string pType { get; set; }
        public Nullable<int> tId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
